# Generated by Django 3.2.8 on 2021-12-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('Email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Objective', models.CharField(max_length=30)),
                ('SchoolSubject', models.CharField(max_length=30)),
                ('SchoolAttended', models.CharField(max_length=30)),
                ('SchoolMarks', models.CharField(max_length=30)),
                ('ClgSubject', models.CharField(max_length=30)),
                ('ClgAttended', models.CharField(max_length=30)),
                ('ClgMarks', models.CharField(max_length=30)),
                ('UniSubject', models.CharField(max_length=30)),
                ('UniAttended', models.CharField(max_length=30)),
                ('UniMarks', models.CharField(max_length=30)),
                ('DOB', models.CharField(max_length=1000)),
                ('Interest', models.CharField(max_length=1000)),
                ('Skills', models.CharField(max_length=1000)),
                ('Experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skills', models.CharField(max_length=30)),
                ('JobTitle', models.CharField(max_length=30)),
                ('JobDescription', models.CharField(max_length=30)),
                ('Salary', models.CharField(max_length=30)),
                ('URL', models.CharField(max_length=30)),
                ('Province', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('DatePosted', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('isCvCreated', models.IntegerField()),
            ],
        ),
    ]
