# Generated by Django 3.2.8 on 2021-12-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='Interest',
        ),
    ]
