# Generated by Django 3.2.8 on 2021-12-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunter', '0003_auto_20211228_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='DoB',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='Interest',
        ),
    ]
