# Generated by Django 3.2.8 on 2021-12-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunter', '0004_auto_20211228_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='DoB',
            field=models.CharField(default='nothing', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='Interest',
            field=models.CharField(default='nothing', max_length=1000),
            preserve_default=False,
        ),
    ]
