# Generated by Django 3.2.8 on 2021-12-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunter', '0005_auto_20211228_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='UniMarks',
            field=models.CharField(default='nothing', max_length=30),
            preserve_default=False,
        ),
    ]
